// Autogenerated by github.com/jxsiss/dbhlp/mysqlparser/gen/run.
// DO NOT EDIT.

package model

type EquipmentType struct {
	Id          int64  `db:"id" gorm:"column:id;primaryKey"`          // int(11)
	Name        string `db:"name" gorm:"column:name"`                 // varchar(45)
	RentalValue string `db:"rental_value" gorm:"column:rental_value"` // decimal(13,2) UNSIGNED
}

type EquipmentTypeList []*EquipmentType

func (p EquipmentTypeList) ToIdMap() map[int64]*EquipmentType {
	out := make(map[int64]*EquipmentType, len(p))
	for _, x := range p {
		out[x.Id] = x
	}
	return out
}

func (p EquipmentTypeList) PluckIds() []int64 {
	out := make([]int64, 0, len(p))
	for _, x := range p {
		out = append(out, x.Id)
	}
	return out
}
