-- MySQL Script generated by MySQL Workbench
-- Fri Aug 10 02:13:07 2018
-- Model: Aviano EER Diagram    Version: 1.5

-- Aviano ERD

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema aviano-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `equipment_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipment_type` ;

CREATE TABLE IF NOT EXISTS `equipment_type` (
                                                `id` INT NOT NULL,
                                                `name` VARCHAR(45) NOT NULL,
    `rental_value` DECIMAL(13,2) UNSIGNED NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `location` ;

CREATE TABLE IF NOT EXISTS `location` (
                                          `id` INT NOT NULL,
                                          `street_address` VARCHAR(100) NOT NULL,
    `city` VARCHAR(50) NOT NULL,
    `state` VARCHAR(2) NOT NULL,
    `zipcode` INT(5) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `zipcode_UNIQUE` (`zipcode` ASC))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipment` ;

CREATE TABLE IF NOT EXISTS `equipment` (
                                           `id` INT NOT NULL,
                                           `name` VARCHAR(45) NOT NULL,
    `equipment_type_id` INT NOT NULL,
    `current_location_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_equipment_equipment_type_idx` (`equipment_type_id` ASC),
    INDEX `fk_equipment_location_idx` (`current_location_id` ASC),
    CONSTRAINT `fk_equipment_equipment_type`
    FOREIGN KEY (`equipment_type_id`)
    REFERENCES `equipment_type` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    CONSTRAINT `fk_equipment_location`
    FOREIGN KEY (`current_location_id`)
    REFERENCES `location` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vehicle_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicle_type` ;

CREATE TABLE IF NOT EXISTS `vehicle_type` (
                                              `id` INT NOT NULL,
                                              `name` VARCHAR(45) NOT NULL,
    `rental_value` DECIMAL(13,2) UNSIGNED NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insurance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `insurance` ;

CREATE TABLE IF NOT EXISTS `insurance` (
                                           `id` INT NOT NULL,
                                           `name` VARCHAR(45) NOT NULL,
    `cost` DECIMAL(13,2) UNSIGNED NOT NULL,
    PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `vehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicle` ;

CREATE TABLE IF NOT EXISTS `vehicle` (
                                         `id` INT NOT NULL,
                                         `brand` VARCHAR(45) NOT NULL,
    `model` VARCHAR(45) NOT NULL,
    `model_year` YEAR NOT NULL,
    `mileage` INT(9) UNSIGNED NOT NULL,
    `color` VARCHAR(45) NOT NULL,
    `vehicle_type_id` INT NOT NULL,
    `current_location_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_vehicle_vehicle_type_idx` (`vehicle_type_id` ASC),
    INDEX `fk_vehicle_location_idx` (`current_location_id` ASC),
    CONSTRAINT `fk_vehicle_vehicle_type`
    FOREIGN KEY (`vehicle_type_id`)
    REFERENCES `vehicle_type` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    CONSTRAINT `fk_vehicle_current_location`
    FOREIGN KEY (`current_location_id`)
    REFERENCES `location` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `customer` ;

CREATE TABLE IF NOT EXISTS `customer` (
                                          `id` INT NOT NULL,
                                          `first_name` VARCHAR(45) NOT NULL,
    `last_name` VARCHAR(45) NOT NULL,
    `dob` DATE NOT NULL,
    `driver_license_number` VARCHAR(12) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `phone` VARCHAR(12) NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `driver_license_number_UNIQUE` (`driver_license_number` ASC),
    UNIQUE INDEX `email_UNIQUE` (`email` ASC))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fuel_option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fuel_option` ;

CREATE TABLE IF NOT EXISTS `fuel_option` (
                                             `id` INT NOT NULL,
                                             `name` VARCHAR(45) NOT NULL,
    `description` VARCHAR(255) NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rental`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rental` ;

CREATE TABLE IF NOT EXISTS `rental` (
                                        `id` INT NOT NULL,
                                        `start_date` DATE NOT NULL,
                                        `end_date` DATE NOT NULL,
                                        `customer_id` INT NOT NULL,
                                        `vehicle_type_id` INT NOT NULL,
                                        `fuel_option_id` INT NOT NULL,
                                        `pickup_location_id` INT NOT NULL,
                                        `drop_off_location_id` INT NOT NULL,
                                        PRIMARY KEY (`id`),
    INDEX `fk_rental_customer_idx` (`customer_id` ASC),
    INDEX `fk_rental_fuel_option_idx` (`fuel_option_id` ASC),
    INDEX `fk_rental_pickup_location_idx` (`pickup_location_id` ASC),
    INDEX `fk_rental_dropoff_location_idx` (`drop_off_location_id` ASC),
    INDEX `fk_rental_vehicle_type_idx` (`vehicle_type_id` ASC),
    CONSTRAINT `fk_rental_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `customer` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    CONSTRAINT `fk_rental_fuel_option`
    FOREIGN KEY (`fuel_option_id`)
    REFERENCES `fuel_option` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    CONSTRAINT `fk_rental_pickup_location`
    FOREIGN KEY (`pickup_location_id`)
    REFERENCES `location` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    CONSTRAINT `fk_rental_dropoff_location`
    FOREIGN KEY (`drop_off_location_id`)
    REFERENCES `location` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    CONSTRAINT `fk_rental_vehicle_type`
    FOREIGN KEY (`vehicle_type_id`)
    REFERENCES `vehicle_type` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `rental_invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rental_invoice` ;

CREATE TABLE IF NOT EXISTS `rental_invoice` (
                                                `id` INT NOT NULL,
                                                `car_rent` DECIMAL(13,2) UNSIGNED NOT NULL,
    `equipment_rent_total` DECIMAL(13,2) UNSIGNED NULL,
    `insurance_cost_total` DECIMAL(13,2) UNSIGNED NULL,
    `tax_surcharges_and_fees` DECIMAL(13,2) UNSIGNED NOT NULL,
    `total_amount_payable` DECIMAL(13,2) UNSIGNED NOT NULL,
    `discount_amount` DECIMAL(13,2) UNSIGNED NULL,
    `net_amount_payable` DECIMAL(13,2) UNSIGNED NOT NULL,
    `rental_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_rental_invoice_rental_idx` (`rental_id` ASC),
    CONSTRAINT `fk_rental_invoice_rental`
    FOREIGN KEY (`rental_id`)
    REFERENCES `rental` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
    ENGINE = InnoDB;
