// Autogenerated by github.com/jxsiss/dbhlp/mysqlparser/gen/run.
// DO NOT EDIT.

package dao

import (
	"gorm.io/gorm"

	"github.com/jxskiss/dbhlp"
)

const tableName_Customer = "customer"

type CustomerDAO interface {
	customerCustomMethods
}

func GetCustomerDAO(conn dbhlp.MySQLConn) CustomerDAO {
	return &customerDAOImpl{
		db: conn,
	}
}

type customerDAOImpl struct {
	db *gorm.DB
}
