// Autogenerated by github.com/jxsiss/dbhlp/mysqlparser/gen/run.
// DO NOT EDIT.

package dao

import (
	"github.com/jxskiss/dbhlp"
	"gorm.io/gorm"
)

const tableName_Customer = "customer"

type CustomerDAO interface {
	customerCustomMethods
}

func GetCustomerDAO(conn dbhlp.DBConn) CustomerDAO {
	return &customerDAOImpl{
		db: conn,
	}
}

type customerDAOImpl struct {
	db *gorm.DB
}
