// This file is autogenerated. DO NOT EDIT.

package dao

import (
	"context"
	"time"

	"github.com/golang/protobuf/proto"
	"github.com/jxskiss/dbgen"
	"github.com/jxskiss/errors"
	"github.com/jxskiss/gopkg/v2/sqlutil"
	"gorm.io/gorm"

	"github.com/jxskiss/dbgen/mysqlparser/example/model"
)

var _ context.Context
var _ time.Time
var _ proto.Message
var _ errors.ErrorGroup
var _ dbgen.Opt
var _ sqlutil.Bitmap
var _ gorm.DB

const tableName_Customer = "customer"

type CustomerDAO interface {
	Get(ctx context.Context, id int64, opts ...dbgen.Opt) (*model.Customer, error)
	GetWhere(ctx context.Context, where string, paramsAndOpts ...interface{}) (*model.Customer, error)
	MGet(ctx context.Context, idList []int64, opts ...dbgen.Opt) (model.CustomerList, error)
	MGetWhere(ctx context.Context, where string, paramsAndOpts ...interface{}) (model.CustomerList, error)
	Update(ctx context.Context, id int64, updates map[string]interface{}, opts ...dbgen.Opt) error
	customerCustomMethods
}

func GetCustomerDAO(conn dbgen.MySQLConn) CustomerDAO {
	return &customerDAOImpl{
		db: conn,
	}
}

type customerDAOImpl struct {
	db *gorm.DB
}

func (p *customerDAOImpl) Get(ctx context.Context, id int64, opts ...dbgen.Opt) (*model.Customer, error) {
	conn := dbgen.PrepareSession(p.db, opts...)
	tableName := tableName_Customer
	var out = &model.Customer{}
	err := conn.WithContext(ctx).Table(tableName).Where("id = ?", id).First(out).Error
	if err != nil {
		return nil, errors.AddStack(err)
	}
	return out, nil
}

func (p *customerDAOImpl) GetWhere(ctx context.Context, where string, paramsAndOpts ...interface{}) (*model.Customer, error) {
	params, opts := dbgen.SplitOpts(paramsAndOpts)
	conn := dbgen.PrepareSession(p.db, opts...)
	tableName := tableName_Customer
	var out = &model.Customer{}
	err := conn.WithContext(ctx).Table(tableName).Where(where, params...).First(out).Error
	if err != nil {
		return nil, errors.AddStack(err)
	}
	return out, nil
}

func (p *customerDAOImpl) MGet(ctx context.Context, idList []int64, opts ...dbgen.Opt) (model.CustomerList, error) {
	conn := dbgen.PrepareSession(p.db, opts...)
	tableName := tableName_Customer
	var out model.CustomerList
	err := conn.WithContext(ctx).Table(tableName).Where("id in (?)", idList).Find(&out).Error
	if err != nil {
		return nil, errors.AddStack(err)
	}
	return out, nil
}

func (p *customerDAOImpl) MGetWhere(ctx context.Context, where string, paramsAndOpts ...interface{}) (model.CustomerList, error) {
	params, opts := dbgen.SplitOpts(paramsAndOpts)
	conn := dbgen.PrepareSession(p.db, opts...)
	tableName := tableName_Customer
	var out model.CustomerList
	err := conn.WithContext(ctx).Table(tableName).Where(where, params...).Find(&out).Error
	if err != nil {
		return nil, errors.AddStack(err)
	}
	return out, nil
}

func (p *customerDAOImpl) Update(ctx context.Context, id int64, updates map[string]interface{}, opts ...dbgen.Opt) error {
	if len(updates) == 0 {
		return errors.New("programming error: empty updates map")
	}
	conn := dbgen.PrepareSession(p.db, opts...)
	tableName := tableName_Customer
	err := conn.WithContext(ctx).Table(tableName).Where("id = ?", id).Updates(updates).Error
	if err != nil {
		return errors.AddStack(err)
	}
	return nil
}
