// Autogenerated by github.com/jxsiss/dbhlp/mysqlparser/gen/run.
// DO NOT EDIT.

package dao

import (
	"context"
	"encoding/json"
	"log"
	"time"

	"github.com/jxskiss/dbhlp"
	"github.com/jxskiss/errors"
	"github.com/jxskiss/gopkg/v2/utils/sqlutil"
	"google.golang.org/protobuf/proto"
	"gorm.io/gorm"

	"github.com/jxskiss/dbhlp/mysqlparser/example/model"
)

var _ context.Context
var _ json.Marshaler
var _ log.Logger
var _ time.Time
var _ dbhlp.Opt
var _ errors.ErrorGroup
var _ sqlutil.LazyBinary
var _ gorm.DB
var _ proto.Message

const tableName_Equipment = "equipment"

type EquipmentDAO interface {
	equipmentCustomMethods
}

func GetEquipmentDAO(conn dbhlp.MySQLConn) EquipmentDAO {
	return &equipmentDAOImpl{
		db: conn,
	}
}

type equipmentDAOImpl struct {
	db *gorm.DB
}
