// Autogenerated by github.com/jxsiss/dbhlp/mysqlparser/gen/run.
// DO NOT EDIT.

package dao

import (
	"github.com/jxskiss/dbhlp"
	"gorm.io/gorm"
)

const tableName_EquipmentType = "equipment_type"

type EquipmentTypeDAO interface {
	equipmentTypeCustomMethods
}

func GetEquipmentTypeDAO(conn dbhlp.DBConn) EquipmentTypeDAO {
	return &equipmentTypeDAOImpl{
		db: conn,
	}
}

type equipmentTypeDAOImpl struct {
	db *gorm.DB
}
