// Autogenerated by github.com/jxsiss/dbhlp/mysqlparser/gen/run.
// DO NOT EDIT.

package dao

import (
	"github.com/jxskiss/dbhlp"
	"gorm.io/gorm"
)

const tableName_Equipment = "equipment"

type EquipmentDAO interface {
	equipmentCustomMethods
}

func GetEquipmentDAO(conn dbhlp.MySQLConn) EquipmentDAO {
	return &equipmentDAOImpl{
		db: conn,
	}
}

type equipmentDAOImpl struct {
	db *gorm.DB
}
