// Autogenerated by github.com/jxsiss/dbhlp/mysqlparser/gen/run.
// DO NOT EDIT.

package dao

import (
	"github.com/jxskiss/dbhlp"
	"gorm.io/gorm"
)

const tableName_FuelOption = "fuel_option"

type FuelOptionDAO interface {
	fuelOptionCustomMethods
}

func GetFuelOptionDAO(conn dbhlp.MySQLConn) FuelOptionDAO {
	return &fuelOptionDAOImpl{
		db: conn,
	}
}

type fuelOptionDAOImpl struct {
	db *gorm.DB
}
