// This file is autogenerated. DO NOT EDIT.

package dao

import (
	"context"
	"time"

	"github.com/golang/protobuf/proto"
	"github.com/jxskiss/dbgen"
	"github.com/jxskiss/errors"
	"github.com/jxskiss/gopkg/v2/sqlutil"
	"gorm.io/gorm"

	"github.com/jxskiss/dbgen/mysqlparser/example/model"
)

var _ context.Context
var _ time.Time
var _ proto.Message
var _ errors.ErrorGroup
var _ dbgen.Opt
var _ sqlutil.Bitmap
var _ gorm.DB

const tableName_FuelOption = "fuel_option"

type FuelOptionDAO interface {
	Get(ctx context.Context, id int64, opts ...dbgen.Opt) (*model.FuelOption, error)
	GetWhere(ctx context.Context, where string, paramsAndOpts ...interface{}) (*model.FuelOption, error)
	MGet(ctx context.Context, idList []int64, opts ...dbgen.Opt) (model.FuelOptionList, error)
	MGetWhere(ctx context.Context, where string, paramsAndOpts ...interface{}) (model.FuelOptionList, error)
	Update(ctx context.Context, id int64, updates map[string]interface{}, opts ...dbgen.Opt) error
	fuelOptionCustomMethods
}

func GetFuelOptionDAO(conn dbgen.MySQLConn) FuelOptionDAO {
	return &fuelOptionDAOImpl{
		db: conn,
	}
}

type fuelOptionDAOImpl struct {
	db *gorm.DB
}

func (p *fuelOptionDAOImpl) Get(ctx context.Context, id int64, opts ...dbgen.Opt) (*model.FuelOption, error) {
	conn := dbgen.PrepareSession(p.db, opts...)
	tableName := tableName_FuelOption
	var out = &model.FuelOption{}
	err := conn.WithContext(ctx).Table(tableName).Where("id = ?", id).First(out).Error
	if err != nil {
		return nil, errors.AddStack(err)
	}
	return out, nil
}

func (p *fuelOptionDAOImpl) GetWhere(ctx context.Context, where string, paramsAndOpts ...interface{}) (*model.FuelOption, error) {
	params, opts := dbgen.SplitOpts(paramsAndOpts)
	conn := dbgen.PrepareSession(p.db, opts...)
	tableName := tableName_FuelOption
	var out = &model.FuelOption{}
	err := conn.WithContext(ctx).Table(tableName).Where(where, params...).First(out).Error
	if err != nil {
		return nil, errors.AddStack(err)
	}
	return out, nil
}

func (p *fuelOptionDAOImpl) MGet(ctx context.Context, idList []int64, opts ...dbgen.Opt) (model.FuelOptionList, error) {
	conn := dbgen.PrepareSession(p.db, opts...)
	tableName := tableName_FuelOption
	var out model.FuelOptionList
	err := conn.WithContext(ctx).Table(tableName).Where("id in (?)", idList).Find(&out).Error
	if err != nil {
		return nil, errors.AddStack(err)
	}
	return out, nil
}

func (p *fuelOptionDAOImpl) MGetWhere(ctx context.Context, where string, paramsAndOpts ...interface{}) (model.FuelOptionList, error) {
	params, opts := dbgen.SplitOpts(paramsAndOpts)
	conn := dbgen.PrepareSession(p.db, opts...)
	tableName := tableName_FuelOption
	var out model.FuelOptionList
	err := conn.WithContext(ctx).Table(tableName).Where(where, params...).Find(&out).Error
	if err != nil {
		return nil, errors.AddStack(err)
	}
	return out, nil
}

func (p *fuelOptionDAOImpl) Update(ctx context.Context, id int64, updates map[string]interface{}, opts ...dbgen.Opt) error {
	if len(updates) == 0 {
		return errors.New("programming error: empty updates map")
	}
	conn := dbgen.PrepareSession(p.db, opts...)
	tableName := tableName_FuelOption
	err := conn.WithContext(ctx).Table(tableName).Where("id = ?", id).Updates(updates).Error
	if err != nil {
		return errors.AddStack(err)
	}
	return nil
}
