// Autogenerated by github.com/jxsiss/dbhlp/mysqlparser/gen/run.
// DO NOT EDIT.

package dao

import (
	"github.com/jxskiss/dbhlp"
	"gorm.io/gorm"
)

const tableName_Location = "location"

type LocationDAO interface {
	locationCustomMethods
}

func GetLocationDAO(conn dbhlp.DBConn) LocationDAO {
	return &locationDAOImpl{
		db: conn,
	}
}

type locationDAOImpl struct {
	db *gorm.DB
}
