// Autogenerated by github.com/jxsiss/dbhlp/mysqlparser/gen/run.
// DO NOT EDIT.

package dao

import (
	"github.com/jxskiss/dbhlp"
	"gorm.io/gorm"
)

const tableName_RentalInvoice = "rental_invoice"

type RentalInvoiceDAO interface {
	rentalInvoiceCustomMethods
}

func GetRentalInvoiceDAO(conn dbhlp.MySQLConn) RentalInvoiceDAO {
	return &rentalInvoiceDAOImpl{
		db: conn,
	}
}

type rentalInvoiceDAOImpl struct {
	db *gorm.DB
}
