// This file is autogenerated. DO NOT EDIT.

package dao

import (
	"context"
	"time"

	"github.com/golang/protobuf/proto"
	"github.com/jxskiss/dbgen"
	"github.com/jxskiss/errors"
	"github.com/jxskiss/gopkg/v2/sqlutil"
	"gorm.io/gorm"

	"github.com/jxskiss/dbgen/mysqlparser/example/model"
)

var _ context.Context
var _ time.Time
var _ proto.Message
var _ errors.ErrorGroup
var _ dbgen.Opt
var _ sqlutil.Bitmap
var _ gorm.DB

const tableName_Rental = "rental"

type RentalDAO interface {
	Get(ctx context.Context, id int64, opts ...dbgen.Opt) (*model.Rental, error)
	GetWhere(ctx context.Context, where string, paramsAndOpts ...interface{}) (*model.Rental, error)
	MGet(ctx context.Context, idList []int64, opts ...dbgen.Opt) (model.RentalList, error)
	MGetWhere(ctx context.Context, where string, paramsAndOpts ...interface{}) (model.RentalList, error)
	Update(ctx context.Context, id int64, updates map[string]interface{}, opts ...dbgen.Opt) error
	rentalCustomMethods
}

func GetRentalDAO(conn dbgen.MySQLConn) RentalDAO {
	return &rentalDAOImpl{
		db: conn,
	}
}

type rentalDAOImpl struct {
	db *gorm.DB
}

func (p *rentalDAOImpl) Get(ctx context.Context, id int64, opts ...dbgen.Opt) (*model.Rental, error) {
	conn := dbgen.PrepareSession(p.db, opts...)
	tableName := tableName_Rental
	var out = &model.Rental{}
	err := conn.WithContext(ctx).Table(tableName).Where("id = ?", id).First(out).Error
	if err != nil {
		return nil, errors.AddStack(err)
	}
	return out, nil
}

func (p *rentalDAOImpl) GetWhere(ctx context.Context, where string, paramsAndOpts ...interface{}) (*model.Rental, error) {
	params, opts := dbgen.SplitOpts(paramsAndOpts)
	conn := dbgen.PrepareSession(p.db, opts...)
	tableName := tableName_Rental
	var out = &model.Rental{}
	err := conn.WithContext(ctx).Table(tableName).Where(where, params...).First(out).Error
	if err != nil {
		return nil, errors.AddStack(err)
	}
	return out, nil
}

func (p *rentalDAOImpl) MGet(ctx context.Context, idList []int64, opts ...dbgen.Opt) (model.RentalList, error) {
	conn := dbgen.PrepareSession(p.db, opts...)
	tableName := tableName_Rental
	var out model.RentalList
	err := conn.WithContext(ctx).Table(tableName).Where("id in (?)", idList).Find(&out).Error
	if err != nil {
		return nil, errors.AddStack(err)
	}
	return out, nil
}

func (p *rentalDAOImpl) MGetWhere(ctx context.Context, where string, paramsAndOpts ...interface{}) (model.RentalList, error) {
	params, opts := dbgen.SplitOpts(paramsAndOpts)
	conn := dbgen.PrepareSession(p.db, opts...)
	tableName := tableName_Rental
	var out model.RentalList
	err := conn.WithContext(ctx).Table(tableName).Where(where, params...).Find(&out).Error
	if err != nil {
		return nil, errors.AddStack(err)
	}
	return out, nil
}

func (p *rentalDAOImpl) Update(ctx context.Context, id int64, updates map[string]interface{}, opts ...dbgen.Opt) error {
	if len(updates) == 0 {
		return errors.New("programming error: empty updates map")
	}
	conn := dbgen.PrepareSession(p.db, opts...)
	tableName := tableName_Rental
	err := conn.WithContext(ctx).Table(tableName).Where("id = ?", id).Updates(updates).Error
	if err != nil {
		return errors.AddStack(err)
	}
	return nil
}
