// Autogenerated by github.com/jxsiss/dbhlp/mysqlparser/gen/run.
// DO NOT EDIT.

package dao

import (
	"github.com/jxskiss/dbhlp"
	"gorm.io/gorm"
)

const tableName_Rental = "rental"

type RentalDAO interface {
	rentalCustomMethods
}

func GetRentalDAO(conn dbhlp.MySQLConn) RentalDAO {
	return &rentalDAOImpl{
		db: conn,
	}
}

type rentalDAOImpl struct {
	db *gorm.DB
}
