// This file is autogenerated. DO NOT EDIT.

package dao

import (
	"context"
	"time"

	"github.com/golang/protobuf/proto"
	"github.com/jxskiss/dbgen"
	"github.com/jxskiss/errors"
	"github.com/jxskiss/gopkg/v2/sqlutil"
	"gorm.io/gorm"

	"github.com/jxskiss/dbgen/mysqlparser/example/model"
)

var _ context.Context
var _ time.Time
var _ proto.Message
var _ errors.ErrorGroup
var _ dbgen.Opt
var _ sqlutil.Bitmap
var _ gorm.DB

const tableName_VehicleType = "vehicle_type"

type VehicleTypeDAO interface {
	Get(ctx context.Context, id int64, opts ...dbgen.Opt) (*model.VehicleType, error)
	GetWhere(ctx context.Context, where string, paramsAndOpts ...interface{}) (*model.VehicleType, error)
	MGet(ctx context.Context, idList []int64, opts ...dbgen.Opt) (model.VehicleTypeList, error)
	MGetWhere(ctx context.Context, where string, paramsAndOpts ...interface{}) (model.VehicleTypeList, error)
	Update(ctx context.Context, id int64, updates map[string]interface{}, opts ...dbgen.Opt) error
	vehicleTypeCustomMethods
}

func GetVehicleTypeDAO(conn dbgen.MySQLConn) VehicleTypeDAO {
	return &vehicleTypeDAOImpl{
		db: conn,
	}
}

type vehicleTypeDAOImpl struct {
	db *gorm.DB
}

func (p *vehicleTypeDAOImpl) Get(ctx context.Context, id int64, opts ...dbgen.Opt) (*model.VehicleType, error) {
	conn := dbgen.GetSession(p.db, opts...)
	tableName := tableName_VehicleType
	var out = &model.VehicleType{}
	err := conn.WithContext(ctx).Table(tableName).Where("id = ?", id).First(out).Error
	if err != nil {
		return nil, errors.AddStack(err)
	}
	return out, nil
}

func (p *vehicleTypeDAOImpl) GetWhere(ctx context.Context, where string, paramsAndOpts ...interface{}) (*model.VehicleType, error) {
	params, opts := dbgen.SplitOpts(paramsAndOpts)
	conn := dbgen.GetSession(p.db, opts...)
	tableName := tableName_VehicleType
	var out = &model.VehicleType{}
	err := conn.WithContext(ctx).Table(tableName).Where(where, params...).First(out).Error
	if err != nil {
		return nil, errors.AddStack(err)
	}
	return out, nil
}

func (p *vehicleTypeDAOImpl) MGet(ctx context.Context, idList []int64, opts ...dbgen.Opt) (model.VehicleTypeList, error) {
	conn := dbgen.GetSession(p.db, opts...)
	tableName := tableName_VehicleType
	var out model.VehicleTypeList
	err := conn.WithContext(ctx).Table(tableName).Where("id in (?)", idList).Find(&out).Error
	if err != nil {
		return nil, errors.AddStack(err)
	}
	return out, nil
}

func (p *vehicleTypeDAOImpl) MGetWhere(ctx context.Context, where string, paramsAndOpts ...interface{}) (model.VehicleTypeList, error) {
	params, opts := dbgen.SplitOpts(paramsAndOpts)
	conn := dbgen.GetSession(p.db, opts...)
	tableName := tableName_VehicleType
	var out model.VehicleTypeList
	err := conn.WithContext(ctx).Table(tableName).Where(where, params...).Find(&out).Error
	if err != nil {
		return nil, errors.AddStack(err)
	}
	return out, nil
}

func (p *vehicleTypeDAOImpl) Update(ctx context.Context, id int64, updates map[string]interface{}, opts ...dbgen.Opt) error {
	if len(updates) == 0 {
		return errors.New("programming error: empty updates map")
	}
	conn := dbgen.GetSession(p.db, opts...)
	tableName := tableName_VehicleType
	err := conn.WithContext(ctx).Table(tableName).Where("id = ?", id).Updates(updates).Error
	if err != nil {
		return errors.AddStack(err)
	}
	return nil
}
