// Autogenerated by github.com/jxsiss/dbhlp/mysqlparser/gen/run.
// DO NOT EDIT.

package dao

import (
	"github.com/jxskiss/dbhlp"
	"gorm.io/gorm"
)

const tableName_Vehicle = "vehicle"

type VehicleDAO interface {
	vehicleCustomMethods
}

func GetVehicleDAO(conn dbhlp.MySQLConn) VehicleDAO {
	return &vehicleDAOImpl{
		db: conn,
	}
}

type vehicleDAOImpl struct {
	db *gorm.DB
}
