package main

import "text/template"

var headerTmpl = template.Must(template.New("header").Parse(`
// This file is autogenerated. DO NOT EDIT.

package {{ .PkgName }}

import (
	"context"
	"time"

	"github.com/golang/protobuf/proto"
	"github.com/jxskiss/dbhlp"
	"github.com/jxskiss/errors"
	"github.com/jxskiss/gopkg/v2/sqlutil"
	"gorm.io/gorm"

	{{ if .ModelPkg }} "{{ .ModelPkg }}" {{ end }}
)

var _ context.Context
var _ time.Time
var _ proto.Message
var _ errors.ErrorGroup
var _ dbhlp.Opt
var _ sqlutil.Bitmap
var _ gorm.DB

`))
